// Generation of the app's img.g.ts.
//
// The file holds the pack, its offset table and the lookups the app's key
// spaces need. Packed images are reached through those lookups; the file
// declares no named const for one.
//
// Only the lookups an app actually uses are emitted: an app with no numeric
// keys gets no numeric table, and one that never looks an image up by string
// gets no name index.

/** Emits a hex literal, split across lines so the file stays readable. */
function hexLit(buf, indent) {
    const hex = buf.toString("hex")
    if (hex.length <= 96) return "hex`" + hex + "`"
    const lines = []
    for (let i = 0; i < hex.length; i += 96) lines.push(indent + "    " + hex.slice(i, i + 96))
    return "hex`\n" + lines.join("\n") + "\n" + indent + "`"
}

// Index tables are u8 up to 255 images and u16le past that, with the matching
// accessor emitted alongside.
function indexTable(values, wide) {
    const buf = Buffer.alloc(values.length * (wide ? 2 : 1))
    values.forEach((v, i) => (wide ? buf.writeUInt16LE(v, i * 2) : (buf[i] = v)))
    return buf
}

function readIndex(name, expr, wide) {
    return wide ? `${name}.getNumber(NumberFormat.UInt16LE, (${expr}) * 2)` : `${name}[${expr}]`
}

/**
 * Emits img.g.ts content.
 *
 * `pack` is what buildPack returned; `names` maps each addressable string key
 * to a pack index; `numeric` maps each numeric key to a pack index. `sources`
 * is the list of files the images were discovered in, for the header.
 */
export function emitImgG(pack, names, numeric, sources) {
    const count = pack.entries.length
    const wide = count > 255
    const L = []

    L.push("// AUTO-GENERATED by @microbit-apps/ui-core/img -- do not edit.")
    L.push("//")
    L.push("// Images are declared with //% img=\"name\" in:")
    for (const s of sources) L.push("//   " + s)
    L.push("// and keyed by the app's key table. Edit an image where it is declared,")
    L.push("// then regenerate; the pixels here are a build product.")
    L.push("namespace _img {")
    L.push("    // Compressed image records end to end; bitmaps.ofCompressed reads one.")
    L.push("    const BLOB = " + hexLit(pack.blob, "    "))
    L.push("    // u16le record offset per image index; identical images share an offset.")
    L.push("    const OFFSETS = " + hexLit(pack.offsets, "    "))
    L.push("    const PACK = new ui.ImagePack(BLOB, OFFSETS)")
    L.push("")
    L.push("    /** Number of image indices in the pack. */")
    L.push("    export const count = " + count)
    L.push("")
    L.push("    /** The image at a pack index, decoded on first use and then cached. */")
    L.push("    export function byIndex(index: number): Bitmap {")
    L.push("        return PACK.get(index)")
    L.push("    }")

    const nameKeys = Object.keys(names).sort()
    if (nameKeys.length > 0) {
        const table = indexTable(nameKeys.map(k => names[k]), wide)
        L.push("")
        L.push("    // String keys, and the pack index of each.")
        L.push("    const KEYS = " + JSON.stringify(nameKeys.join(",")) + ".split(\",\")")
        L.push("    const KEY_INDEX = " + hexLit(table, "    "))
        L.push("")
        L.push("    /** Pack index for a string key, or -1 when no image has it. */")
        L.push("    export function indexOfName(name: string): number {")
        L.push("        const i = KEYS.indexOf(name)")
        L.push("        if (i < 0) return -1")
        L.push("        return " + readIndex("KEY_INDEX", "i", wide))
        L.push("    }")
    }

    const numKeys = Object.keys(numeric).map(Number)
    if (numKeys.length > 0) {
        // A flat table indexed by the key itself. Entries are index + 1, so
        // 0 means the key names no image.
        const size = Math.max(...numKeys) + 1
        const values = new Array(size).fill(0)
        for (const k of numKeys) values[k] = numeric[k] + 1
        L.push("")
        L.push("    // Numeric key -> pack index + 1; 0 means the key names no image.")
        L.push("    const NUM_INDEX = " + hexLit(indexTable(values, wide), "    "))
        L.push("")
        L.push("    /** Pack index for a numeric key, or -1 when no image has it. */")
        L.push("    export function indexOfKey(key: number): number {")
        L.push("        if (key < 0 || key >= " + size + ") return -1")
        L.push("        return " + readIndex("NUM_INDEX", "key", wide) + " - 1")
        L.push("    }")
    }

    L.push("")
    L.push("    /**")
    L.push("     * The image for one of the app's keys. An unknown key gives the pack's")
    L.push("     * fallback image, or undefined when `nullIfMissing` is set.")
    L.push("     */")
    L.push("    export function get(")
    L.push("        id: string | number,")
    L.push("        nullIfMissing?: boolean,")
    L.push("    ): Bitmap | undefined {")
    const lookups = []
    if (nameKeys.length > 0) lookups.push('typeof id == "string" ? indexOfName(<string>id)')
    if (numKeys.length > 0) lookups.push("indexOfKey(<number>id)")
    if (lookups.length === 2) L.push("        const index = " + lookups[0] + " : " + lookups[1])
    else if (nameKeys.length > 0) L.push("        const index = indexOfName(<string>id)")
    else if (numKeys.length > 0) L.push("        const index = indexOfKey(<number>id)")
    else L.push("        const index = -1")
    L.push("        if (index < 0 && nullIfMissing) return undefined")
    L.push("        // An out-of-range index is what yields the pack's fallback.")
    L.push("        return PACK.get(index)")
    L.push("    }")
    L.push("}")
    return L.join("\n") + "\n"
}
